- name: Import playbooks from another file, helps to keep them manageable when you have lots
  import_playbook: playbooks/my_playbook.yml

- name: Import exercise playbooks
  import_playbook: playbooks/exercises.yml
