---
- name: Pip3 install numpy into a virtualenv at ~/Desktop/
  ansible.builtin.pip:
    name:
      - numpy
    virtualenv: ~/Desktop/exercise07_venv/
    virtualenv_command: "{{ python_version }} -m virtualenv"

- name: Pip3 install scipy into the virtualenv if Python 3.9 is used
  ansible.builtin.pip:
    name:
      - scipy
    virtualenv: ~/Desktop/exercise07_venv/
  when: python_version == "python3.9"

- name: Pip3 install additional modules needed
  ansible.builtin.pip:
    name:
      - "{{ exercises_exercise07_pip_extra_module }}"
    virtualenv: ~/Desktop/exercise07_venv/
  loop: "{{ pip_extras }}"
  loop_control:
    loop_var: exercises_exercise07_pip_extra_module
  when: pip_extras is defined
