---
- name: Copy template file to home directory - single var
  ansible.builtin.template:
    src: template
    dest: ~/Desktop/hello.txt
    mode: "0644"
  vars:
    passed_in_variable: hello world!

- name: Copy template file home directory - two vars
  ansible.builtin.template:
    src: template
    dest: ~/Desktop/{{ file_name }}
    mode: "0644"
  vars:
    passed_in_variable: hello world!
    file_name: world.txt

- name: Copy template file home directory - two vars one loop
  ansible.builtin.template:
    src: template
    dest: ~/Desktop/{{ exercises_exercise02_sol_file_name }}
    mode: "0644"
  vars:
    passed_in_variable: hello world!
  loop: [hello_loop.txt, world_loop.txt]
  loop_control:
    loop_var: exercises_exercise02_sol_file_name
