---
- name: Copy hello.txt to home directory
  ansible.builtin.copy:
    src: hello.txt
    dest: ~/Desktop/
    mode: "0644"

- name: Create/write to world.txt in home directory
  ansible.builtin.shell:
    cmd: echo "hello world!" >> world.txt
    chdir: ~/Desktop/
  changed_when: true
